# Site settings
title: "React & JavaScript Developer | 김수현"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "SooHyun Kim"
resume_title: "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email: "s2ksh_77@naver.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "010-7413-8388"
resume_contact_address: "경기도 수원시 거주"

resume_header_contact_info: "경기도 수원시 거주 • 010-7413-8388 • s2ksh_77@naver.com"
display_header_contact_info: "false"

resume_header_intro: "
      안녕하세요. React / JavaScript 웹 개발자 김수현 입니다. </br>

      React, JavaScript, Mobx, node.js, GIT 등의 기술을 사용하여 </br>

      효율적인 비즈니스 로직 및 서비스 별 렌더링 최적화와 함께

      안정적인 서비스 제공을 목표로 하는 개발자 입니다. </br>

      현재 TmaxWAPL 이라는 업무 협업 웹 어플리케이션에서 'Note' 모듈의 FrontEnd / BackEnd를 담당하고 있습니다. </br>

      BackEnd ( 회사 제품 : Spring 기반 프레임워크 ProObject, Tibero, Spring Boot )
"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: true
resume_section_links: true
resume_section_associations: true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/s2ksh77"
  #resume_twitter_url: "http://twitter.com/jglovier"
  #resume_dribbble_url: "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/s2ksh77"
  resume_instagram_url: "https://www.instagram.com/soo_hyuniiii/"
  resume_website_url: "https://tmax.wapl.ai/"
  #resume_medium_url: "https://medium.com/@jglovier"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
